---

version: '3.3'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    container_name: elastic
    environment:
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
    - ./configs/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    - ./configs/elasticsearch/users:/usr/share/elasticsearch/config/users
    - ./configs/elasticsearch/users_roles:/usr/share/elasticsearch/config/users_roles
    - elastic:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
    - "9200:9200"
    networks:
    - net

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    container_name: kibana
    volumes:
    - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - "5601:5601"
    networks:
    - net
    depends_on:
    - elastic

volumes:
  elastic:
    driver: local

networks:
  net:
