---

cluster.name: "elasticstack"
network.host: 0.0.0.0
http.host: 0.0.0.0
bootstrap.memory_lock: true

discovery.zen:
  ping.unicast.hosts:
  - 127.0.0.1
  minimum_master_nodes: 1

xpack.license.self_generated.type: trial

node:
  name: elastic
  data: true
  master: true
  ingest: true

xpack:
  sql.enabled: true
  security:
    enabled: true
    audit.enabled: false
  ml.enabled: true
  watcher.enabled: true
  monitoring:
    enabled: true
    collection.enabled: true
    elasticsearch.collection.enabled: true

